#### Recursion
* Recursion consists of a repeated function call with shifting arguments, building up a stack.
* It requires an ending condition to return a result and prevent infinite recursion

In [1]:
# Factorial is n!
def factorial(factor):
    if factor  < 0:
        return 0
    elif factor == 1:
        return 1 # Last stack push hits here, so 2 * 1 is first return
    else:
        return factor * factorial(factor - 1) # Stack Builds here
print(factorial(5)) # 5 * (4 * (3 * (2 * 1)))

120


In [9]:
def greatestCommonFactor(a, b):
    '''
    Modulo gets us to greatest common factor.
    When modulo is 0, you know you have a common factor
    '''
    if b == 0:
        return a
    else:
        return greatestCommonFactor(b, a%b)
greatestCommonFactor(90, 20)

10

In [12]:
def leastCommonMultiple(a, b):
    return abs(a * b)/greatestCommonFactor(a, b) # Absolute value of product of a & b/ GCF or GCD of a & b
leastCommonMultiple(12, 33)

132.0

In [28]:
def fibonacciSequence(n):
    if n in [0, 1]:
        return 1
    return fibonacciSequence(n - 1) + fibonacciSequence(n - 2)

In [29]:
print(fibonacciSequence(7))

21


In [35]:
class LinkedListNode:
    def __init__(self, nextNode, content):
        self.next = nextNode
        self.content = content
def reverseLinkedList(node):
    if node.next:
        reverseLinkedList(node.next)
    print(node.content)
bar = LinkedListNode(None, 'bar')
foo = LinkedListNode(bar, 'foo')
reverseLinkedList(foo)

bar
foo


# Tree Operations
* A tree is a structure with a root node and one or more nodes connected to the root
* For our purposes here, we'll model the connected nodes as left and right.
* Three traversals possible, **pre-Order**, **post-Order**, and **in-Order**

In [38]:
class Node:
    def __init__(self, left, right, data):
        self.left = left
        self.right = right
        self.data = data

f = Node(None, None, 'f')
g = Node(None, None, 'g')
e = Node(None, None, 'e')
d = Node(None, None, 'd')        
b = Node(d, e, 'b')
a = Node(f, g, 'a')
c = Node(a, b, 'c') # Root


In [39]:
def preOrderTraversal(root):
    '''
    If left exists, print and continue left (printing along the way) as long as possible
    Once left is null print right if exists and continue left as long as possible
    Work back up stack
    Print - Left - Right - PLR
    '''
    print(root.data)
    if root.left:
        preOrderTraversal(root.left)
    if root.right:
        preOrderTraversal(root.right)
preOrderTraversal(c)

c
a
f
g
b
d
e


In [42]:
def postOrderTraversal(node):
    '''
    Travel left if not null
    Travel right if not null
    Print once at a leaf
    Left - Right - Print LRP
    '''
    if node.left:
        postOrderTraversal(node.left)
    if node.right:
        postOrderTraversal(node.right)
    print(node.data)
postOrderTraversal(c)

f
g
a
d
e
b
c


In [44]:
def inOrderTraversal(node):
    '''
    Travel left if possible
    Print when not
    Travel right
    This ends up printing the tree "Bottom Up" in pattern left leaf left parent right leaf all the way up
    '''
    if node.left:
        inOrderTraversal(node.left)
    print(node.data)
    if node.right:
        inOrderTraversal(node.right)
inOrderTraversal(c)

f
a
g
c
d
b
e


# Sort
* Sorting is a two step process
* First, pick a pivot node
* Then perform the partitioning process so that all elements to the left of the pivot are less than the pivot and all nodes to the right are greater than the pivot
* The main quicksort function doesn't really do much - just directs the divide and conquer, the partitioning does all the work

In [53]:
# [4, 5, 33, 17, 3, 21, 1, 16]

def swap(numbers, x, i):
    # TL;DR - x becomes i, i becomes x - note that these two are *indexes*,  
    temp = numbers[x] # the number to be moved
    print('x is:', str(x))
    print('i is:', str(i))
    numbers[x] = numbers[i] # Insert the value at i to where x was
    numbers[i] = temp # Put x where i was
    

def partition(numbers, start, end):
    pivot = numbers[end] # Last element of slice
    print('Pivot:' + str(pivot))
    x = start - 1 # First element of slice - note that this will be -1 in first pass
    print('Start:' + str(x))
    for i in range(start, end): # Iterate over length of slice
        if numbers[i] < pivot:
            '''
            Okay - so the way this works is that x increments when the number being tested is in its final position
            for this round. It doesn't increment when the number is bigger than the pivot - so x and i become
            unequal and when swap runs next it will move positions
            '''
            x += 1 # Pointer to what the element is that will be swapped
            print('numbers[i] is:', str(numbers[i]))
            print('Number series swap will happen on' + str(numbers))
            swap(numbers, x, i) 
    swap(numbers, x+1, end) # last node in slice passed in swaps into wherever the start node incremented to
    return x + 1

def quicksort(numbers, start, end):
    if start < end:
        p = partition(numbers, start, end)
        quicksort(numbers, start, p - 1) # Slice smaller than p
        quicksort(numbers, p + 1, end) # Slice bigger than p
    return numbers

sort_me = [4, 5, 33, 17, 3, 21, 1, 16]
quicksort(sort_me, 0, len(sort_me) - 1)

Pivot:16
Start:-1
numbers[i] is: 4
Number series swap will happen on[4, 5, 33, 17, 3, 21, 1, 16]
x is: 0
i is: 0
numbers[i] is: 5
Number series swap will happen on[4, 5, 33, 17, 3, 21, 1, 16]
x is: 1
i is: 1
numbers[i] is: 3
Number series swap will happen on[4, 5, 33, 17, 3, 21, 1, 16]
x is: 2
i is: 4
numbers[i] is: 1
Number series swap will happen on[4, 5, 3, 17, 33, 21, 1, 16]
x is: 3
i is: 6
x is: 4
i is: 7
Pivot:1
Start:-1
x is: 0
i is: 3
Pivot:4
Start:0
numbers[i] is: 3
Number series swap will happen on[1, 5, 3, 4, 16, 21, 17, 33]
x is: 1
i is: 2
x is: 2
i is: 3
Pivot:33
Start:4
numbers[i] is: 21
Number series swap will happen on[1, 3, 4, 5, 16, 21, 17, 33]
x is: 5
i is: 5
numbers[i] is: 17
Number series swap will happen on[1, 3, 4, 5, 16, 21, 17, 33]
x is: 6
i is: 6
x is: 7
i is: 7
Pivot:17
Start:4
x is: 5
i is: 6


[1, 3, 4, 5, 16, 17, 21, 33]

# Binary Search
* Binary search works by repeatedly splitting the search space in half. It decide which half to head to by testing where the search candidate is smaller or bigger than the comparison number.

In [1]:
def binarySearch(numbers, target):
    low = 0
    high = len(numbers) - 1
    while low <= high:
        mid = (low + high) // 2
        comp = numbers[mid]
        if comp == target:
            return mid # Target found, return idx
        elif comp < target:
            low = mid + 1 # Search in higher half
        else:
            high = mid - 1 # Search in lower half
    return -1 # Not found
        

In [62]:
binarySearch(sort_me, 16)

4

# Greedy
* Greedy algorithms at their heart are **Optimal Activity Selection** problems operating forward in time.
* Two basic properties of this algorith class:
    1. Optimal substructure: Each subproblem reflects global problem. Specifically, each subset of the problem operated on must exhibit the global structure so coherence is reached.
    2. Greedy choice: From the local optimum, the global optimum is reached without revisiting local subproblems. In this example - if you've reached the maximum size of subset and can pick something with an earlier end time, that choice is even greedier and should be chosen

In [90]:
class Activity:
    
    def __init__(self, activityName, start, end):
        self.activityName = activityName
        self.start = start
        self.end = end

a = Activity("a", 600, 720)
b = Activity("b", 1200, 1380)
c = Activity("c", 1020, 1140)
d = Activity("d", 600, 630)
e = Activity("e", 1290, 1380)
f = Activity("f", 750, 810)
g = Activity("g", 1200, 1320)
h = Activity("h", 1020, 1170)
i = Activity("i", 960, 1140) 
j = Activity("j", 900, 1020)

def selectOptimalActivities(activitySet):
    optimalSet = []
    activitySet.sort(key=lambda x: x.end)
    if len(activitySet) > 0:
        optimalSet.append(activitySet[0]) # Always take first if sorted list non-empty
    for i in range(1, len(activitySet) - 1):
        if activitySet[i].start >= optimalSet[len(optimalSet) - 1].end:
            optimalSet.append(activitySet[i])
    return optimalSet

In [94]:
optimalActivitySet = selectOptimalActivities([a, b, c, d, e, f, g, h, i, j])
activityNames = ""
for a in aSet:
    activityNames += a.activityName + " "
print(activityNames)

d f j c g 


# Dynamic Programming
* Dynamic programming breaks a problem into subproblems and solves those first, leading to the solution to the main problem
* This is the GOTO when you have a cost function and a value function with a defined capacity. i.e. the tuples ${(($400, 20), ($200, 12), ($50, 1))}$ and capacity 4
* The classic example of this is **the knapsack problem** - what are the optimal items to purchase/steal to maximize value with a knapsack of size n 
* Naive solution - brute force all combinations - bad - an ${O(n)^2}$ runtime
* Dynamic programming offers a better way - solves "sub-knapsacks" first - modeled as a matrix with rows as items and columns as knapsack sizes
* Steps:
    1. Fill in the value function to that item's row
    2. For each row in the column, this represents the "best guess" of item to steal
    3. In each row, you steal the item in that row, or the item above it (subject to capacity constraints)
    4. The order of rows doesn't matter
    5. The final row is **always the optimal solution** for what we've seen so far

In [119]:
class StealableItem:
    
    def __init__(self, value, weight, name):
        self.weight = weight
        self.value = value
        self.name = name

stealableItems = []
stealableItems.append(StealableItem(3000, 4, "Stereo"));
stealableItems.append(StealableItem(2000, 3, "Laptop"));
stealableItems.append(StealableItem(1500, 1, "Guitar"));
stealableItems.append(StealableItem(2000, 1, "iPhone"));

In [125]:
import numpy as np
def knapsack(stealableItems, sackSize):
    space = np.zeros([len(stealableItems), sackSize])
    for r in range(len(stealableItems)):
        for c in range(sackSize):
            if r == 0:
                space[r][c] = stealableItems[r].value # Always take first rows value
                print(space[r][c])
            elif c - stealableItems[r].weight < 0:
                    space[r][c] = space[r-1][c] # Weight of this row's item is too heavy, take previous rows
            else:
                # Maximize value by taking the previous rows value or this row + previous row's remaining space
                space[r][c] = max(space[r-1][c], stealableItems[r].value + space[r - 1][c - stealableItems[r].weight])
    print(space)
                
    

In [126]:
knapsack(stealableItems, 4)

3000.0
3000.0
3000.0
3000.0
[[3000. 3000. 3000. 3000.]
 [3000. 3000. 3000. 5000.]
 [3000. 4500. 4500. 5000.]
 [3000. 5000. 6500. 6500.]]


In [129]:
inputArray = '10 \nyellowShirt\nredHat\nblackShirt\nbluePants\nredHat\npinkHat\nblackShirt\nyellowShirt\ngreenPants\ngreenPants'''

In [130]:
inputArray.splitlines()

['10 ',
 'yellowShirt',
 'redHat',
 'blackShirt',
 'bluePants',
 'redHat',
 'pinkHat',
 'blackShirt',
 'yellowShirt',
 'greenPants',
 'greenPants']

In [131]:
#!/bin/python3

import math
import os
import random
import re
import sys


import numpy as np
#
# Complete the 'featuredProduct' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING_ARRAY products as parameter.
#

# max(product day t)
# featured -> day t + 1
# if tie for max return all products alphabetically, choose last

def featuredProduct(products):
    product_dict = {}
    for p in products:
        if p not in product_dict:
            product_dict[p] = 1
        else:
            product_dict[p] += 1
    filtered_product_dict = {}
    max_sales = max(product_dict.values())
    print(max_sales)
    for key in product_dict:
        print(key)
        if product_dict[key] == max_sales:
            filtered_product_dict[key] = product_dict[key]
    max_sale_items = filtered_product_dict.keys()
    sorted_max_sale_items = sorted(max_sale_items)
    print(sorted_max_sale_items[-1])
if __name__ == '__main__':

NameError: name 'products' is not defined

In [132]:
my_list = [4,3,2,5]

In [137]:
for n in range(2):
    my_list[len(my_list) - (n + 1)] += 2

In [138]:
my_list

[4, 3, 4, 7]